module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#edeeef",
        "error": "#ba1a1a",
        "surface-container-low": "#f3f4f5",
        "primary-fixed": "#dce1ff",
        "on-primary-container": "#90a8ff",
        "on-secondary-fixed": "#121c28",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#f39461",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-highest": "#e1e3e4",
        "secondary-fixed": "#d9e3f4",
        "secondary-fixed-dim": "#bdc7d8",
        "on-background": "#191c1d",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdbcb",
        "secondary": "#555f6d",
        "tertiary-container": "#6e2c00",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d6e0f1",
        "on-tertiary-fixed": "#341100",
        "on-primary-fixed": "#00164e",
        "surface-container-high": "#e7e8e9",
        "on-surface": "#191c1d",
        "on-secondary-container": "#596372",
        "inverse-surface": "#2e3132",
        "on-error": "#ffffff",
        "outline-variant": "#c5c5d3",
        "inverse-primary": "#b6c4ff",
        "surface-bright": "#f8f9fa",
        "on-tertiary-fixed-variant": "#773205",
        "surface": "#f8f9fa",
        "tertiary-fixed-dim": "#ffb691",
        "on-surface-variant": "#444651",
        "tertiary": "#4b1c00",
        "on-secondary-fixed-variant": "#3e4755",
        "background": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#4059aa",
        "outline": "#757682",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "primary-container": "#1e3a8a",
        "primary": "#00236f",
        "surface-dim": "#d9dadb",
        "on-primary-fixed-variant": "#264191",
        "primary-fixed-dim": "#b6c4ff",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        xs: "8px",
        xl: "80px",
        base: "4px",
        lg: "48px",
        gutter: "24px",
        sm: "16px",
        md: "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    }
  },
   plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}